version: "3.7"
services:
  database:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - /data/db
      - /data/configdb
    restart: always
  frontend:
    container_name: blogs-client
    build:
      dockerfile: Dockerfile.dev
      context: "./frontend"
    volumes:
      - /usr/src/app/node_modules
      - ./frontend:/usr/src/app
      - /usr/src/app/.next
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: unless-stopped
  backend:
    container_name: blogs-backend
    build:
      dockerfile: Dockerfile.dev
      context: "./backend"
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    depends_on:
      - database
    environment:
      - PORT=${PORT}
      - MONGO_URL= ${MONGO_URL}
    ports:
      - 8000:8000
    restart: unless-stopped
